on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Dummy
    steps:
      - name: A dummy action to enable protected branch out-of-date check
        run: echo "dummy action"

